#!/bin/bash

echo "Parameter 0: $0"
echo "Parameter 1: $1"
echo "Parameter 2: $2"
echo "Parameter 3: $3"
echo "Parameter 4: $4"
echo "Parameter 5: $5"
echo "Parameter 6: $6"
echo "Parameter 7: $7"
echo "Parameter 8: $8"
echo "Parameter 9: $9"
# Falsch:
# echo "Parameter 10: $10"
# echo "Parameter 11: $11"

# Richtig:
shift 9
echo "Parameter 10: $1"
echo "Parameter 11: $2"
echo "Parameter 12: $3"
echo "Parameter 13: $4"
echo "Parameter 14: $5"
echo "Parameter 15: $6"

exit 0
